apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
