pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-app-backend"
        IMAGE_TAG = "latest"
        REGISTRY = "docker.io/ash271182"
        KUBE_CONFIG = credentials('KUBE_CONFIG')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ash271182/apps.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'cd my-app'
                sh 'docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-credentials', url: 'https://index.docker.io/v1/']) {
                    sh 'docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'KUBE_CONFIG']) {
                    sh 'cd my-app'
                    sh 'kubectl apply -f k8s/'
                }
            }
        }
    }
}
