pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-app-backend"
        IMAGE_TAG = "latest"
        REGISTRY = "ash271182"
        KUBE_CONFIG = credentials('KUBE_CONFIG')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ash271182/apps/blob/main/my-app'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t /: -f docker/Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-credentials', url: 'https://index.docker.io/v1/']) {
                    sh 'docker push /:'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'KUBE_CONFIG']) {
                    sh 'kubectl apply -f k8s/'
                }
            }
        }
    }
}
